### ISSUE TITLE
Command "termius push" running extremely slow

### ISSUE THREAD

**Issue by rudziankou** [Crystalnix/termius-cli#134]
Hi, folks,

Using Termius CLI I created 1000 new hosts (I'd like to add 7000 hosts). Storage file contains 35k lines for now. Then I'm trying to push my changes to Termius cloud. It takes a huge amount of time, hours...  I'm wondering is it normal? Is it possible to make it faster? Does Termius application have a host number limit? Will Termius work fine with that amount of hosts, without any lags?

Thanks!

**Comment by rudziankou** [comment]
Before I added 1000 hosts (200 at the time). Today I added 1400 hosts at the time and did push after that. I received an error:

<html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.12.2</center>
</body>
</html>

**Comment by HobbledGrubs** [comment]
I am having the same problem. Any news on this?

**Comment by rudziankou** [comment]
@HobbledGrubs,
I switched over to Royal TSX. I paid $50 for a license, working great!
